config/routes.rb
class AdminConstraint
  def matches?(request)
    return false unless request.session["warden.user.backend_admin.key"]
    return true
  end
end

Rails.application.routes.draw do

  require 'sidekiq/web'
  require 'sidekiq-scheduler/web'
  mount Sidekiq::Web => '/backend/sidekiq', :constraints => AdminConstraint.new

  mount ActionCable.server, at: '/cable'

  devise_for :users, only: :passwords, controllers: { :passwords => "frontend/users/passwords" }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :backend do
    root to: "home#index"
    resources :exchanges do
      resources :exchange_pairs, only: [:index, :show]
    end
    devise_for :admins, :controllers => { :sessions => "backend/admins/sessions", registrations: "backend/admins/registrations" }

    resources :opportunities, only: [:index, :show]
    resources :markets, only: [:index, :show] do
      collection do
        get :all
      end
      member do
        patch :unwatch
        patch :watch
      end
      resources :reports, only: [:index, :show]
      resources :pairs, only: [:index, :show, :edit, :update] do
        member do
          patch :unwatch
          patch :watch
        end
        resources :tickers, only: [:index, :show]
        resources :order_books, only: [:index, :show]
        resources :trade_histories, only: [:index, :show]
      end
    end
  end

  namespace :api, format: 'json' do
    namespace :v1 do
      devise_for :users, controllers: { :sessions => "backend/users/sessions", registrations: "backend/users/registrations", confirmations: 'backend/users/confirmations' }
      namespace :public do
        resources :markets, only: [:index, :show]
        resources :market_infos, only: [:index]
        resources :contact_us, only: [:create]
        resources :asset_infos, only: [:index, :show] do
          collection do
            get :all
          end
        end
        resources :exchanges, only: [:index]
      end
      namespace :private do
        resources :alarms, only: [:index, :create] do
          collection do
            patch :toggle_activation
            patch :destroy_alarm
            patch :edit_alarm
          end
        end
        resources :portfolio, only: [:index] do
          collection do
            post :add_asset
            patch :remove_asset
            patch :edit_asset
          end
        end
      end
      resources :sessions, only: [:create]
      resources :registrations, only: [:create]
    end
  end

  namespace :frontend do
    root to: "home#index"
  end

  root to: "frontend/home#index"
  get "*path", to: "frontend/home#index"

end

app/models/pair.rb
class Pair < ApplicationRecord
  has_many :tickers
  has_many :order_books
  has_many :trade_histories
  belongs_to :exchange
  belongs_to :market

  scope :active, -> { where(is_active: true) }
  scope :watched, -> { where(is_watched: true) }

  def self.with_last_ticker
    with_last_ticker_id.map{|p| p if p.last_ticker}.compact
  end

  scope :with_last_ticker_id, -> {
    where.not(last_ticker_id: nil)
  }

  # Callback called from ticker after_commit
  def update_market_spread
    market.update_spread
  end

  def get_order_book
    RestExchange::OrderBook::Fetcher.new(self).call
  end

  def get_trade_history
    RestExchange::TradeHistory::Fetcher.new(self).call
  end

  def get_ticker
    if exchange.has_ticker_endpoint
      RestExchange::Ticker::Fetcher.new(self).call
    else
      puts("There is no ticker endpoint for #{exchange.name}")
    end
  end


  def exists_in_exchange exchange_array

  end

  def get_user_pair_path
    exchange.get_user_pair_path
  end


  def last_ticker
    Ticker.find(last_ticker_id) rescue nil
  end

end

app/controllers/backend/admins/registrations_controller.rb
class Backend::Admins::RegistrationsController < ::Devise::RegistrationsController
  #layout "backend/connection"
end

app/controllers/backend/admins/sessions_controller.rb
class Backend::Admins::SessionsController < ::Devise::SessionsController
  #layout "backend/connection"
end

app/controllers/backend/base_controller.rb
class Backend::BaseController < ApplicationController
  before_action :authenticate_backend_admin!
  layout 'backend.html.erb'
end

app/controllers/backend/exchange_pairs_controller.rb
class Backend::ExchangePairsController < Backend::BaseController
  def index
    @exchange = Exchange.find(params[:exchange_id])
    @pairs = @exchange.pairs
  end

  def show
    @pair = Exchange.find(params[:id])
  end

  # def unwatch
  #  pair = Exchange.find(params[:id])
  #  pair.update_column(:is_watched, false)
  #  redirect_to backend_market_reports_path(params[:market_id])
  # end
end

app/controllers/backend/exchanges_controller.rb
class Backend::ExchangesController < Backend::BaseController

  before_action :find_exchange, only: [:edit, :show, :update]

  def index
    @exchanges = Exchange.all
  end

  def new
    @exchange = Exchange.new
  end

  def create
    @exchange = Exchange.new(exchange_params)
    if @exchange.save
      redirect_to backend_exchanges_path
    else
      @errors = @exchange.errors.full_messages
      render :new
    end
  end

  def update
    if @exchange.update_attributes(exchange_params)
      redirect_to backend_exchanges_path
    else
      @errors = @exchange.errors.full_messages
      render :edit
    end
  end

  def edit
  end

  def show
  end

  private
  def exchange_params
    params.require(:exchange).permit(:id, :get_user_pair_path, :country)
  end

  def find_exchange
    @exchange = Exchange.find(params[:id])
  end
end

app/controllers/backend/home_controller.rb
class Backend::HomeController < Backend::BaseController
  def index; end
end

app/controllers/backend/markets_controller.rb
class Backend::MarketsController < Backend::BaseController


  def index
    @markets = Market.of_interest.order(spread: :desc)#.limit(150)
      # Market
      #   .left_joins(:pairs)
      #   .group(:id)
      #   .order('COUNT(pairs.id) DESC')
      #   .limit(50)
  end

  def all
    @markets = Market.all.page params[:page]
  end

  def show
    @market = Market.find(params[:id])
    #binding.pry
    @graph_data = @market.pairs.map{ |p| { name: p.exchange.name, data: p.tickers.order(created_at: :desc).limit(100).map{|t| [t.created_at.to_i, t.last.to_f]} } }
  end

  def unwatch
    market = Market.find(params[:id])
    market.update_column(:is_watched, false)
    redirect_to backend_markets_path
  end

  def watch
    market = Market.find(params[:id])
    market.update_column(:is_watched, true)
    redirect_to backend_markets_path
  end


end

app/controllers/backend/opportunities_controller.rb
class Backend::OpportunitiesController < Backend::BaseController


  def index
    @markets = Market.of_interest.where(has_opportunity: true).where(spread: 4..99).order(spread: :desc)
      # Market
      #   .left_joins(:pairs)
      #   .group(:id)
      #   .order('COUNT(pairs.id) DESC')
      #   .limit(50)
  end

  def show
    @market = Market.find(params[:id])
  end

  def unwatch
    market = Market.find(params[:id])
    market.update_column(:is_watched, false)
    redirect_to backend_markets_path
  end


end

app/controllers/backend/order_books_controller.rb
class Backend::OrderBooksController < Backend::BaseController


  def index
    @pair = Pair.find(params[:pair_id])
    @order_books = @pair.order_books
  end

  def show
    @order_book = OrderBook.find(params[:id])
  end


end

app/controllers/backend/pairs_controller.rb
class Backend::PairsController < Backend::BaseController


  def index
    @market = Market.find(params[:market_id])
    @pairs = @market.pairs
  end

  def show
    @pair = Pair.find(params[:id])
  end

  def unwatch
    pair = Pair.find(params[:id])
    pair.update_column(:is_watched, false)
    pair.market.update_column(:spread, nil)
    redirect_to backend_market_reports_path(params[:market_id])
  end

  def watch
    pair = Pair.find(params[:id])
    pair.update_column(:is_watched, true)
    pair.market.update_column(:spread, nil)
    redirect_to backend_market_reports_path(params[:market_id])
  end

  def update
    @pair = Pair.find(params[:id])
    if @pair.update_attributes(pair_params)
      @pair.market.update_column(:spread, nil)
      redirect_to backend_market_pairs_path(@pair.market)
    else
      @errors = @pair.errors.full_messages
      render :edit
    end
  end

  def edit
    @pair = Pair.find(params[:id])
  end

  private
  def pair_params
    params.require(:pair).permit(:id, :market_id)
  end

end

app/controllers/backend/reports_controller.rb
class Backend::ReportsController < Backend::BaseController


  def index
    @market = Market.find(params[:market_id])
    @reports = @market.reports.order(id: :desc).limit(50)
  end

  def show
    @report = Report.find(params[:id])
  end


end

app/controllers/backend/tickers_controller.rb
class Backend::TickersController < Backend::BaseController


  def index
    @pair = Pair.find(params[:pair_id])
    @tickers = @pair.tickers.order(id: :desc).limit(100)
  end

  def show
    @ticker = Ticker.find(params[:id])
  end


end

app/controllers/backend/trade_histories_controller.rb
class Backend::TradeHistoriesController < Backend::BaseController


  def index
    @pair = Pair.find(params[:pair_id])
    @trade_histories = @pair.trade_histories
  end

  def show
    @trade_history = TradeHistory.find(params[:id])
  end


end

app/controllers/backend/users/confirmations_controller.rb
# frozen_string_literal: true

class Backend::Users::ConfirmationsController < ::Devise::ConfirmationsController# < DeviseController
  # GET /resource/confirmation/new
  def new
    self.resource = resource_class.new
  end

  # POST /resource/confirmation
  def create
    self.resource = resource_class.send_confirmation_instructions(resource_params)
    yield resource if block_given?

    if successfully_sent?(resource)
      respond_with({}, location: after_resending_confirmation_instructions_path_for(resource_name))
    else
      respond_with(resource)
    end
  end

  # GET /resource/confirmation?confirmation_token=abcdef
  def show
    self.resource = resource_class.confirm_by_token(params[:confirmation_token])
    yield resource if block_given?

    if resource.errors.empty?
      #set_flash_message!(:notice, :confirmed)
      redirect_to "/sign_in"
      #respond_with_navigational(resource){
        #render json: {msg: 'confirmation success'}, status: 201
      #}
    else
      redirect_to "/sign_in"
      #respond_with_navigational(resource.errors, status: :unprocessable_entity){ render :new }
    end
  end

  protected

    # The path used after resending confirmation instructions.
    def after_resending_confirmation_instructions_path_for(resource_name)
      is_navigational_format? ? new_session_path(resource_name) : '/'
    end

    # The path used after confirmation.
    def after_confirmation_path_for(resource_name, resource)
      # binding.pry
      # if signed_in?(resource_name)
      #   signed_in_root_path(resource)
      # else
      #   new_session_path(resource_name)
      # end
    end

    def translation_scope
      'devise.confirmations'
    end
end

app/controllers/backend/users/registrations_controller.rb
class Backend::Users::RegistrationsController < ::Devise::RegistrationsController
  #layout "backend/connection"
end

app/controllers/backend/users/sessions_controller.rb
class Backend::Users::SessionsController < ::Devise::SessionsController
  #layout "backend/connection"

  def create
    #binding.pry
    self.resource = warden.authenticate!(auth_options)
    set_flash_message!(:notice, :signed_in)
    sign_in(resource_name, resource)
    yield resource if block_given?
    respond_with resource, location: after_sign_in_path_for(resource)
  end

end

app/views/backend/pairs/edit.html.erb
<%#= binding.pry %>
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>

<%= form_for [:backend, @pair.market, @pair] do |f| %>

  <%= f.label :market_id %>
  <%= f.select :market_id, Market.of_interest.order(name: :asc).map{|m| ["#{m.name} (#{m.id})", m.id]} %>

  <%= f.submit 'submit' %>

  <%= link_to "Listing", backend_exchanges_path %>

<% end %>

<script type="text/javascript">
  $(document).ready(function() {
    $('#pair_market_id').select2();
  });
</script>

app/views/backend/pairs/index.html.erb
<%= link_to "Show Market", backend_market_path(@market), class: 'btn btn-success', data: { turbolinks: false } %>
<%= link_to "Go to Markets List", backend_markets_path, class: 'btn btn-success', data: { turbolinks: false } %>

<table class="table table-hover">
  <thead>
    <tr>
      <th>#</th>
      <th>Name</th>
      <th>Base Currency</th>
      <th>Quote Currency</th>
      <th>Min Trade Size</th>
      <th>Exchange</th>
      <th>Original Payload</th>
    </tr>
  </thead>
  <tbody>
    <% @pairs.each do |pair| %>
      <tr>
        <th scope="row"><%= pair.id %></th>
        <td><%= pair.name %></td>
        <td><%= pair.base_currency %></td>
        <td><%= pair.quote_currency %></td>
        <td><%= pair.min_trade_size %></td>
        <td><%= pair.exchange.name %></td>
        <td><%= pair.original_payload %></td>
        <td><%= link_to "Details", backend_market_pair_path(pair.market, pair), class: 'btn btn-success', data: { turbolinks: false } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/backend/pairs/show.html.erb
<%= link_to "Pairs List", backend_market_pairs_path(@pair.market), class: 'btn btn-success', data: { turbolinks: false } %>
<table class="table table-hover">
  <thead>
    <tr>
      <th>#</th>
      <th>Name</th>
      <th>Base Currency</th>
      <th>Quote Currency</th>
      <th>Min Trade Size</th>
      <th>Exchange</th>
      <th>Is Watched</th>
      <th>Original Payload</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row"><%= @pair.id %></th>
      <td><%= @pair.name %></td>
      <td><%= @pair.base_currency %></td>
      <td><%= @pair.quote_currency %></td>
      <td><%= @pair.min_trade_size %></td>
      <td><%= @pair.exchange.name %></td>
      <td><%= @pair.is_watched %></td>
      <td><%= @pair.original_payload %></td>
    </tr>
  </tbody>
</table>



<section class="text-center">
  <%= link_to 'Show Tickers', backend_market_pair_tickers_path(@pair.market, @pair), class: 'btn btn-info', data: { turbolinks: false } %>
  <%= link_to 'Show Order Books', backend_market_pair_order_books_path(@pair.market, @pair), class: 'btn btn-info', data: { turbolinks: false } %>
  <%= link_to 'Show Trade History', backend_market_pair_trade_histories_path(@pair.market, @pair), class: 'btn btn-info', data: { turbolinks: false } %>
  <% if @pair.is_watched %>
    <%= link_to "Unwatch pair #{@pair.id}", unwatch_backend_market_pair_path(@pair.market.id, @pair.id), method: :patch, class: "btn btn-danger", data: { confirm: 'Are you sure ?' } %>
  <% else %>
    <%= link_to "Watch pair #{@pair.id}", watch_backend_market_pair_path(@pair.market.id, @pair.id), method: :patch, class: "btn btn-danger", data: { confirm: 'Are you sure ?' } %>
  <% end %>
</section>

<hr>

<section class="text-center">
  <%= "Currently belongs to Market : #{@pair.market.name}" %>
</section>

<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>

<section class="text-center">
  <%= form_for [:backend, @pair.market, @pair] do |f| %>

    <%= f.label "Change Pair's Market to : " %>
    <%= f.select :market_id, Market.of_interest.order(name: :asc).map{|m| ["#{m.name} (#{m.id})", m.id]} %>

    <%= f.submit 'submit' %>


  <% end %>
</section>

<hr>

<%= link_to "Go to Exchange List", backend_exchanges_path, class: 'btn btn-success', data: { turbolinks: false } %>
<%= link_to "Go to Markets List", backend_markets_path, class: 'btn btn-success', data: { turbolinks: false } %>

<script type="text/javascript">
  $(document).ready(function() {
    $('#pair_market_id').select2();
  });
</script>